id: PFFF99FE5
initial_creation_type: input
source_metadata:
  Title: Pratimālakṣaṇavivaraṇam
  Editor: Dr. Banarsi Lal
  Publisher: Central Institute of Higher Tibetan Studies (CIHTS)
  Place of Publication: Sarnath, Varanasi, India
  Year: '2003'
  Pratimālakṣaṇavivaraṇam:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:52:23.519226'
last_modified_at: '2022-03-08T16:52:23.519234'
